### ISSUE TITLE
Using Loki plugin for other input than docker

### ISSUE THREAD

**Issue by jgsqware** [eeddaann/fluent-plugin-loki#2]
Hi, 

Is this plugin could be use with any input plugin from fluentd?

Using for example the syslog input and Loki output?

How the labels are added if not docker logging driver?

Thanks

**Comment by eeddaann** [comment]
Hi,
the plan is to support any input plugin from fluentd.
I would like to test it with some common input plugins before i'll release it. 
which plugins do you recommend to test?
if you will attach sample configurations I can try to create integration tests for these use cases.

**Comment by jgsqware** [comment]
I would love to have the syslog working tbh ;)

Btw happy new year from Belgium!

**Comment by eeddaann** [comment]
Happy new year!
following this issue I decided to [add some sample configurations of fluentd inputs](https://github.com/eeddaann/fluent-plugin-loki#usage-examples-for-common-fluentd-inputs) that I tested with this plugin as an output plugin.
The good news are that syslog input worked for me as a charm!
