### ISSUE TITLE
naming conflict with official fluent-plugin-loki

### ISSUE THREAD

**Issue by RobertHeim** [eeddaann/fluent-plugin-loki#3]
Hi @eeddaann 

we appreciate the work you do and open sourcing it! Unfortunately, there is a naming conflict with the fluent-plugin-loki developed within the loki repositories:

* https://github.com/grafana/loki/tree/master/fluentd/fluent-plugin-loki

Since this is hard to spot and [confuses](https://github.com/grafana/loki/issues/535) people when following the official loki guide [on setting up fluent-plugin-loki](https://github.com/grafana/loki/tree/master/fluentd/fluent-plugin-loki), I wonder if you would mind changing the name of [your gem file](https://rubygems.org/gems/fluent-plugin-loki/versions/0.2.0)?

Best

**Comment by eeddaann** [comment]
Hi @RobertHeim,
I understand the problem, I'm fine with changing the name.
changing the following line would be enough?
https://github.com/eeddaann/fluent-plugin-loki/blob/92347b7465b4f5569e4946243ada97e2ad57970f/fluent-plugin-loki.gemspec#L4
Is it safe to do it? I'm afraid to affect users of this gem...

**Comment by RobertHeim** [comment]
the grafana one was renamed.
