### ISSUE TITLE
Mistaken/dubious README.md sample configuration

### ISSUE THREAD

**Issue by alexbarcelo** [eeddaann/fluent-plugin-loki#4]
Maybe I am mistaken, but shouldn't the `@type` line in the README.md file be `loki` instead of `http`?

I have not used this plugin, I was trying to understand how to use it, and I still am not sure if there's that mistake or I am missing something big.

**Comment by eeddaann** [comment]
seems like it's my mistake.. try to put ```loki``` and it should work, i'll fix the readme soon. thanks for spotting it. and feel free to contact me if you need help with the configuration

**Comment by nwehr** [comment]
+1 on this issue. It took me quite awhile to figure out what was going on.

**Comment by eeddaann** [comment]
Thanks for the reminder @nwehr !
